// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwoiwnjyyhobwtwsnyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3b2l3bmp5eWhvYnd0d3NueWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzcwOTYsImV4cCI6MjA2NDA1MzA5Nn0.Jg9KyR09mlcyI5EKNI2EQzWfR0WMrjA4B9Jy3k0QC7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);